{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c49a6351-bb46-4a92-a42e-8144642d0c5c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import yfinance as yf\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Streamlit 페이지 설정\n",
    "st.set_page_config(page_title=\"Stock Analysis\", layout=\"wide\")\n",
    "\n",
    "# 제목\n",
    "st.title(\"Stock Analysis with Dividends Reinvestment\")\n",
    "\n",
    "# 사용자 입력\n",
    "ticker = st.text_input(\"Enter stock ticker\", \"AAPL\")\n",
    "period = st.selectbox(\"Select period\", [\"1y\", \"5y\", \"10y\"])\n",
    "\n",
    "# 데이터 다운로드\n",
    "@st.cache\n",
    "def load_data(ticker, period):\n",
    "    stock = yf.Ticker(ticker)\n",
    "    stock_data = stock.history(period=period, actions=True)\n",
    "    return stock_data\n",
    "\n",
    "stock_data = load_data(ticker, period)\n",
    "\n",
    "# 데이터 처리\n",
    "stock_data['Dividend'] = stock_data['Dividends'].fillna(0)\n",
    "stock_data['Price'] = stock_data['Close']\n",
    "\n",
    "# 배당금 및 주가 시뮬레이션\n",
    "initial_shares = 1\n",
    "shares = initial_shares\n",
    "price_list = []\n",
    "dividend_list = []\n",
    "investment_value = []\n",
    "\n",
    "for idx, row in stock_data.iterrows():\n",
    "    dividends = row['Dividend']\n",
    "    price = row['Price']\n",
    "    \n",
    "    # 재투자된 주식 수\n",
    "    shares += (dividends / price)\n",
    "    \n",
    "    # 주가와 투자 가치 저장\n",
    "    price_list.append(price)\n",
    "    dividend_list.append(dividends)\n",
    "    investment_value.append(shares * price)\n",
    "\n",
    "# 데이터 프레임 생성\n",
    "simulated_data = pd.DataFrame({\n",
    "    'Date': stock_data.index,\n",
    "    'Price': price_list,\n",
    "    'Dividend': dividend_list,\n",
    "    'Investment Value': investment_value\n",
    "})\n",
    "\n",
    "# 그래프 그리기\n",
    "fig, ax1 = plt.subplots(figsize=(14, 7))\n",
    "\n",
    "# 주가 선 그래프\n",
    "ax1.plot(simulated_data['Date'], simulated_data['Price'], color='tab:blue', label='Stock Price')\n",
    "ax1.set_xlabel('Date')\n",
    "ax1.set_ylabel('Stock Price', color='tab:blue')\n",
    "ax1.tick_params(axis='y', labelcolor='tab:blue')\n",
    "\n",
    "# 재투자 후 투자 가치 선 그래프\n",
    "ax2 = ax1.twinx()\n",
    "ax2.plot(simulated_data['Date'], simulated_data['Investment Value'], color='tab:green', linestyle='--', label='Investment Value')\n",
    "ax2.set_ylabel('Investment Value', color='tab:green')\n",
    "ax2.tick_params(axis='y', labelcolor='tab:green')\n",
    "\n",
    "# 배당금 막대 그래프\n",
    "fig.tight_layout()\n",
    "plt.bar(simulated_data['Date'], simulated_data['Dividend'], color='tab:orange', alpha=0.5, label='Dividend')\n",
    "\n",
    "# 범례 추가\n",
    "fig.legend(loc=\"upper left\", bbox_to_anchor=(0.1,0.9))\n",
    "\n",
    "# Streamlit에 그래프 표시\n",
    "st.pyplot(fig)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
